[package]
name = "unnamed_protocol_client"
version = "0.1.0"
authors = ["Zack <zphixon@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
float_eq = "0.3.1"
image = "0.23.4"
#rustls = "0.17.0"
#webpki = "0.21.3"
#webpki-roots = "0.19.0"
