froggi = pageStyle? pageExpression*

pageStyle = '{' ( '(' IDENTIFIER styleList ')' )* '}'

pageExpression =
    | '(' IDENTIFIER? inlineStyle? (text | pageExpression)+ ')'
    | '(' '^' text inlineStyle? text ')'
    | '(' '&' text inlineStyle? text ')'
    | '(' '#' text ')'

inlineStyle = '{' styleList '}'

styleList = IDENTIFIER+

text = ('\'' | '"') ANYTHING ('\'' | '"')
