froggi = [pageStyle] {pageExpression}

pageStyle = "{" { "(" IDENTIFIER styleList ")" } "}"

pageExpression =
    | "(" [IDENTIFIER] [inlineStyle] ((text {text}) | (pageExpression {pageExpression})) ")"
    | "(" "^" text [inlineStyle] [text] ")"
    | "(" "&" text [inlineStyle] (text {text}) ")"
    | "(" "#" text ")"

inlineStyle = "{" styleList "}"

styleList = { IDENTIFIER | style }

text = ("\"" | "'") ANYTHING ("\"" | "'")
