[package]
name = "froggi"
version = "0.1.0"
authors = ["Zack <zphixon@gmail.com>"]
edition = "2018"

[features]
default = []
layout = ["druid"]

[dependencies]
float_eq = "0.3.1"
hex = "0.4.2"

[dependencies.druid]
version = "0.6.0"
optional = true

[[bin]]
name = "verify_markup"
test = false
path = "bin/verify_markup.rs"

[[bin]]
name = "to_html"
test = false
path = "bin/to_html.rs"
