[package]
name = 'froggi'
version = '0.1.0'
authors = ['Zack <zphixon@gmail.com>']
edition = '2018'

[features]
default = ['markup']
markup = []
ui = [] # each backend have its own feature? or just let clients do whatever?

[dependencies]
hex = '0.4.3'
uuid = {version = '0.8.2', features = ['v4']}

[[bin]]
name = 'verify_markup'
test = false
path = 'verify_markup.rs'

[[bin]]
name = 'to_html'
test = false
path = 'to_html.rs'
